Tokenizer
lee-tammy/CodeU-Summer-2017 pull request #3
Opened 2017-06-13 14:36 UTC by Weech4theStars

2017-06-16 21:09 UTC, alanhzhao commented on src/codeu/chat/util/Tokenizer.java
> +	//TODO: add javadoc
Comments don't need to be TODOs.

2017-06-16 21:14 UTC, alanhzhao requested changes

2017-06-16 21:14 UTC, alanhzhao commented on src/codeu/chat/util/Tokenizer.java
> +	public String next() throws IOException {
Please handle the exception instead of exposing it in the public interface.

2017-06-16 21:14 UTC, alanhzhao commented on src/codeu/chat/util/Tokenizer.java
> +public final class Tokenizer {
Fix indentation for this class, and add a javadoc.

2017-06-16 21:14 UTC, alanhzhao commented on src/codeu/chat/util/Tokenizer.java
> +      } else if (peek() == '"') {
Use String.equals to compare strings

2017-06-16 21:14 UTC, alanhzhao commented on src/codeu/chat/util/TokenizerTest.java
> +public class TokenizerTest {
Add test for no args.

2017-06-16 21:14 UTC, alanhzhao commented on src/codeu/chat/util/Tokenizer.java
> +        throw new IOException();  //add error message
Please add the message.

2017-06-17 00:11 UTC, Weech4theStars commented on src/codeu/chat/util/Tokenizer.java
> +      } else if (peek() == '"') {
peek() returns a char, so this line isn't comparing strings. I could cast the char to a string and then use String.equals, but that feels weird. Let me know what makes the most sense to do :)

2017-06-18 21:58 UTC, alanhzhao requested changes

2017-06-18 21:58 UTC, alanhzhao commented on src/codeu/chat/util/Tokenizer.java
> +      } else if (peek() == '"') {
You're right, this is fine as is.

2017-06-18 21:58 UTC, alanhzhao commented on src/codeu/chat/client/commandline/Panel.java
> +    if(command != null) {
nit: keep the space after if

2017-06-18 21:58 UTC, alanhzhao commented on src/codeu/chat/util/Tokenizer.java
> +public final class Tokenizer {
Sorry, I meant add a short description of the class here, and also describe public methods (i.e. next()).

2017-06-18 21:58 UTC, alanhzhao commented on src/codeu/chat/util/Tokenizer.java
> +    } catch(IOException e) {
nit: add space before (

2017-06-18 21:58 UTC, alanhzhao commented on src/codeu/chat/util/Tokenizer.java
> +		return source.length() - at;
Don't mix tabs and spaces. This codebase generally uses spaces, so I would stick to that.

2017-06-18 21:58 UTC, alanhzhao commented on src/codeu/chat/client/commandline/Chat.java
> +    for (String token = tokenizer.next(); token != null; token = tokenizer.next()){
nit: add space between ) and {

2017-06-18 22:59 UTC, Weech4theStars commented on src/codeu/chat/util/Tokenizer.java
> +public final class Tokenizer {
oh sorry for the misunderstanding - I can add that!

2017-06-20 20:53 UTC, ruan-andy commented
I added javadoc and fixed some tabs spaces.

2017-06-21 01:07 UTC, merged