Server info fix
lee-tammy/CodeU-Summer-2017 pull request #7
Opened 2017-06-25 21:46 UTC by adsnaider

The first commit actually fixes the Server info.
The second commit only deals with formatting the Server.java file.

2017-06-25 22:01 UTC, alanhzhao requested changes

2017-06-25 22:01 UTC, alanhzhao commented on src/codeu/chat/client/commandline/Chat.java
> +                Time.now()).inMs() * Math.pow(10, -3)));
Just divide by 1000. Cast ms to double if you want decimal.

2017-06-25 22:01 UTC, alanhzhao commented on src/codeu/chat/server/Server.java
> +              32)) {
fix break: keep parameters together

2017-06-25 22:01 UTC, alanhzhao commented on src/codeu/chat/server/Server.java
> +      user = controller.newUser(relayUser.id(), relayUser.text(),
fix break: keep parameters together

2017-06-25 22:01 UTC, alanhzhao commented on src/codeu/chat/server/Server.java
> +      // person who
fix break

2017-06-25 22:01 UTC, alanhzhao commented on src/codeu/chat/server/Server.java
> +          relayConversation.text(), user.id, relayConversation.time());
Also, if you must break a list of parameters into multiple lines, put one on each line.

2017-06-25 22:01 UTC, alanhzhao commented on src/codeu/chat/server/Server.java
> +      message = controller.newMessage(relayMessage.id(), user.id,
fix break: parameters

2017-06-25 22:01 UTC, alanhzhao commented on src/codeu/chat/server/Server.java
> +      final Uuid conversationId, final Uuid messageId) {
fix break: parameters

2017-06-25 22:01 UTC, alanhzhao commented on src/codeu/chat/server/Server.java
> +        relay.write(id, secret, relay.pack(user.id, user.name, user.creation),
fix break: parameters

2017-06-25 22:01 UTC, alanhzhao commented on src/codeu/chat/server/Server.java
> +            content);
Don't break here. If you must break, keep parameters `author, conversation,  content ` together. Try setting your max line length to 100 characters--that's the standard at Google.

2017-06-26 02:30 UTC, adsnaider commented on src/codeu/chat/server/Server.java
> +            content);
Oh. Interesting. I always had it setup at 80 for C++ (following the google style guide). I didn't realize that they were different for java.

2017-06-26 02:50 UTC, adsnaider commented on src/codeu/chat/server/Server.java
> +      // person who
Even after changing the default line wrap to 100, the formatter keeps trying to split it into three different lines...

2017-06-26 02:55 UTC, adsnaider commented on src/codeu/chat/client/commandline/Chat.java
> +                Time.now()).inMs() * Math.pow(10, -3)));
Done

2017-06-26 03:02 UTC, alanhzhao requested changes

2017-06-26 03:02 UTC, alanhzhao commented on src/codeu/chat/client/commandline/Chat.java
> +          System.out.format("  Duration   : %s sec\n", (int) (Time.duration(info.startTime,
Don't cast to int. Approved for merge after fixing this.

2017-06-26 03:15 UTC, adsnaider commented on src/codeu/chat/client/commandline/Chat.java
> +          System.out.format("  Duration   : %s sec\n", (int) (Time.duration(info.startTime,
Done

2017-06-26 03:35 UTC, alanhzhao approved these changes

2017-06-26 04:10 UTC, merged